name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
            docker build -t simple-node .
            docker tag simple-node YOUR_DOCKER_HUB/simple-node:latest
            
    - name: push to docker hub
      uses: docker/build-push-action@v3
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        tags: ${{secrets.DOCKER_USERNAME}}/simple-node:latest        

